### ISSUE TITLE
System.InvalidOperationException   HResult=0x80131509   Message=Illegal point type 'Move'.

### ISSUE THREAD

**Issue by peterennis** [adrientetar/Fonte#3]
```
System.InvalidOperationException
  HResult=0x80131509
  Message=Illegal point type 'Move'.
  Source=Fonte.Data
  StackTrace:
   at Fonte.Data.Path.get_CanvasPath() in C:\ae\Fonte\Fonte.Data\Path.cs:line 127
   at Fonte.Data.Layer.CollectPaths(Func`2 predicate) in C:\ae\Fonte\Fonte.Data\Layer.cs:line 718
   at Fonte.Data.Layer.get_ClosedCanvasPath() in C:\ae\Fonte\Fonte.Data\Layer.cs:line 309
   at Fonte.App.Utilities.Drawing.DrawFill(Layer layer, CanvasDrawingSession ds, Single rescale, Color color) in C:\ae\Fonte\Fonte.App\Utilities\Drawing.cs:line 134
   at Fonte.App.Controls.DesignCanvas.OnRegionsInvalidated(CanvasVirtualControl sender, CanvasRegionsInvalidatedEventArgs args) in C:\ae\Fonte\Fonte.App\Controls\DesignCanvas.xaml.cs:line 231
```

Drawing this path, right click, select reverse and crash

![Capture701](https://user-images.githubusercontent.com/140737/68554996-41387c80-03e0-11ea-9e74-e9291d9212e0.png)

![Capture702](https://user-images.githubusercontent.com/140737/68555048-86f54500-03e0-11ea-89f5-7f443c68f6ec.png)
![Capture700](https://user-images.githubusercontent.com/140737/68555049-86f54500-03e0-11ea-9f03-a69590f6ba1c.png)

**Comment by peterennis** [comment]
@adrientetar 
Tested this a few times and it reliably crashes on reverse paths.
Let me know of other things to test and how you want reports.
Getting up to speed on coding will take longer.

**Comment by adrientetar** [comment]
ty, join discord.gg / YDKJuzG for discussion
