### ISSUE TITLE
ERROR: booleanoperations 0.9.0 has requirement fonttools>=4.0.2, but you'll have fonttools 3.44.0 which is incompatible

### ISSUE THREAD

**Issue by peterennis** [adrientetar/Fonte#6]
Following readme instructions for TruFont env to use it with Fonte and I get this:

```
Successfully built cu2qu pyclipper
ERROR: booleanoperations 0.9.0 has requirement fonttools>=4.0.2, but you'll have fonttools 3.44.0 which is incompatible.
```

![Capture711](https://user-images.githubusercontent.com/140737/69010080-7c6f0a00-0910-11ea-9edc-3d6f8e891d71.png)

```
(TF_ENV_DIR) C:\ae\TF_ENV_DIR>fonttools
Traceback (most recent call last):
  File "C:\Users\peter\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\peter\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ae\TF_ENV_DIR\Scripts\fonttools.exe\__main__.py", line 9, in <module>
  File "c:\ae\tf_env_dir\lib\site-packages\fontTools\__main__.py", line 24, in main
    mod = 'fontTools.'+sys.argv[1]
IndexError: list index out of range

(TF_ENV_DIR) C:\ae\TF_ENV_DIR>
```

and indeed, checking the file system lib I see:

![Capture712](https://user-images.githubusercontent.com/140737/69010294-20f24b80-0913-11ea-9d0c-bb5d60c516d1.png)

**Comment by peterennis** [comment]
Uninstall fonttools and reinstall

![Capture713](https://user-images.githubusercontent.com/140737/69010379-0a98bf80-0914-11ea-9870-d4bd7fbf96bd.png)

Looks like a catch 22:

```
ERROR: ufolib 2.3.2 has requirement fonttools<4,>=3.1.2, but you'll have fonttools 4.0.2 which is incompatible.
ERROR: trufont 0.6.2 has requirement fonttools[lxml,ufo]<4,>=3.40.0, but you'll have fonttools 4.0.2 which is incompatible.
```

How to proceed?

**Comment by peterennis** [comment]
Using VS Code it prompts to select python interpreter and shows this:

![Capture714](https://user-images.githubusercontent.com/140737/69010545-abd44580-0915-11ea-9bb2-332fb1619716.png)

32 bit and 64 bit, with different locations.

32 bit installed via readme process and 64 bit from Python download.

Then looking in TruFont requirements I see:

![Capture715](https://user-images.githubusercontent.com/140737/69010591-15545400-0916-11ea-916c-367417ea473c.png)
